[bootstrap.packages]
# GUI applications
## ghostty
"brew-cask:ghostty" = { os = ["macos"] }
"brew-cask:firefox" = { os = ["macos"] }
## obsidian
"brew-cask:obsidian" = { os = ["macos"] }
"flatpak-user:obsidian" = { os = ["linux"] }
