[bootstrap.packages]
"brew:ffmpeg" = { os = "macos", version = "latest" }
"apt:ffmpeg" = { os = "linux", version = "latest" }
"brew:yt-dlp" = { os = "macos", version = "latest" }
"apt:yt-dlp" = { os = "linux", version = "latest" }
